using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace QuestBase.UI
{
    public class QuestObjectDefinitions : MonoBehaviour
    {
        public static readonly string QuestObjectViewTypeFilePath = $"{Application.dataPath}/QuestTemplate/Scripts/AutoGenerated/QuestObjectViewType.cs";
    }
}
