using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace QuestBase.UI
{
    public class UITextDefinitions
    {
        public static SystemLanguage[] AvailableLanguages = new SystemLanguage[]
        {
            SystemLanguage.Japanese,
            SystemLanguage.English,
        };

        public const string LangTextCsvPath = "UI/LanguageText";
        public static readonly string LangEnumFilePath = $"{Application.dataPath}/QuestTemplate/Scripts/AutoGenerated/LangTextLabel.cs";
    }
}
