using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace QuestBase.UI
{
    public class UIWindowDefinitions : MonoBehaviour
    {
        public static readonly string WinodwTypeFilePath = $"{Application.dataPath}/QuestTemplate/Scripts/AutoGenerated/UIWindowType.cs";
        public const string WindowPrefabTablePath = "ScriptableObjects/WindowPrefabTable";
    }
}
